# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
