# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_foto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='pics.Album'),
        ),
    ]
